### PR TITLE
Fix up missing newline in os-signal runner termination logging.

### PR DESCRIPTION
**Pull request by wooly**
### Description

Add a missing newline in signal-termination log.

### Testing

Logs should look better.

### CODE REVIEW

**Review by nprizal — APPROVED** [review]
Not again!! 😩

**Comment by nprizal** [comment]
should we merge to `main`?

**Comment by wooly** [comment]
> Not again!! 😩

Inorite

**Comment by wooly** [comment]
I am not precious about this one, it can go in whenever.

**Pull request merged**
